meta: the final migration
tloncorp/landscape pull request #142
Opened 2023-04-12 22:21 UTC by arthyn

This concludes a 2 year stint of this desk being named incorrectly. Also renames agents to their more appropriate names and moves agents from %groups that should be in %landscape instead.

We'll need to yell from the rooftops for third parties to know about all the moves which can be seen below: 

## desk
%garden -> %landscape

## agents

### renames
- %settings-store -> %settings

### from old groups
- %s3-store -> %storage

### from new groups
- %hark
- %contacts

### unchanged
- %docket
- %treaty
- %reel
- %bait

### final list
- %bait
- %contacts
- %docket
- %hark
- %reel
- %settings
- %storage
- %treaty

2023-05-03 20:50 UTC, ashelkovnykov commented
See [these](https://github.com/tloncorp/landscape/issues/149#issuecomment-1533691452) [comments](https://github.com/tloncorp/landscape/issues/149#issuecomment-1533730354) on #149

2023-05-08 15:59 UTC, ashelkovnykov requested changes

2023-05-08 15:59 UTC, ashelkovnykov commented on desk/app/settings.hoon
> +        ?.  .^(? %gu bas)
Missing latest changes from #163

2023-05-08 15:59 UTC, ashelkovnykov commented on desk/app/storage.hoon
> +      ?.  .^(? %gu bas)
Same as above

2023-05-08 15:59 UTC, ashelkovnykov commented on desk/sur/groups.hoon
> +--
nit: missing newline

2023-05-08 19:03 UTC, ashelkovnykov approved these changes
Seems fine to me. The ordering has been inverted and this branch is now attempting to merge into the one from #163, correct?

2023-05-08 19:07 UTC, arthyn commented
right because the other is preceeding and I wanted to hide those changes here

2023-07-13 17:55 UTC, arthyn commented
New fun and interesting changes 🤣

2023-09-20 17:19 UTC, merged